
import os

from yacs.config import CfgNode as CN


_C = CN()

# DATASET related params
_C.DATASET = CN()
_C.DATASET.SUB_DATASET_NAMES = []
_C.DATASET.SUB_DATASET_IS_HIGH = []
_C.DATASET.SUB_DATASET_SUFFIX_PERSON = []
_C.DATASET.SUB_DATASET_SUFFIX_CLOTH = []
_C.DATASET.SUB_DATASET_PAIRS_PATH = []
_C.DATASET.SUB_DATASET_PAIRS_PATH_VAL = []
_C.DATASET.ROTATION_DEGREE_PERSON = 10
_C.DATASET.ROTATION_DEGREE_CLOTH = 5
_C.DATASET.FLIP_PROB = 0.5
_C.DATASET.MAX_ROTATION_DEGREE_PERSON = 10
_C.DATASET.MAX_ROTATION_DEGREE_CLOTH = 5
_C.DATASET.ADDITIONAL_FLAVORS = tuple()
_C.DATASET.RESIZE_SHAPE = None
_C.DATASET.TRUNCATE_POSE = True
_C.DATASET.FILL_FOR_IMAGE_RGB = 246
_C.DATASET.NUM_ERODE_ITERATIONS = 1
_C.DATASET.NUM_ERODE_ITERATIONS_SOBEL = 0
_C.DATASET.ERODE_KERNEL_SIZE = 7
_C.DATASET.ERODE_KERNEL_SIZES = [21, 11]
_C.DATASET.MAX_SHIFT_PERSON = [0.1, 0.1]  # in ratio
_C.DATASET.MAX_SHIFT_CLOTH = [0.05, 0.05]  # in ratio
_C.DATASET.SCALE_RANGE_PERSON = [0.9, 1.1]
_C.DATASET.SCALE_RANGE_CLOTH = [0.95, 1.05]
_C.DATASET.USE_GT_WARPED_CLOTH = False
# from Dinov2
_C.DATASET.NORMALIZATION_MEAN = [0.485, 0.456, 0.406]
_C.DATASET.NORMALIZATION_STD = [0.229, 0.224, 0.225]

_C.TRAIN = CN()
_C.TRAIN.L2_LAMBDA = 0.0
_C.TRAIN.L1_LAMBDA = 0.0
_C.TRAIN.LR_INIT_SCALE = 2.0**13
_C.TRAIN.LR_DECAY = 0.01
_C.TRAIN.LR_GROWTH_FACTOR = 2
_C.TRAIN.LR_BACKOFF_FACTOR = 0.5
_C.TRAIN.LR_GROWTH_INTERVAL = 4000
_C.TRAIN.TRAIN_LORA = False
_C.TRAIN.LORA_RANK = 4
_C.TRAIN.LORA_ALPHA = None
# How often the conditionals are omitted. 0.0 means no classifier free guidance
_C.TRAIN.CFG_PROB = 0.0
_C.TRAIN.MULTI_CFG = False
_C.TRAIN.FIND_UNUSED_PARAMETERS = False
_C.TRAIN.GRADIENT_AS_BUCKET_VIEW = False
_C.TRAIN.COLD_START = False
_C.TRAIN.ZERO_START = False
_C.TRAIN.EDGE_LOSS_WEIGHT = 1.0
# Trivial flow loss
_C.TRAIN.LOSS_L1_WEIGHT = 1.0
_C.TRAIN.LOSS_WEIGHT_MASK = 1.0
_C.TRAIN.LOSS_TV_WEIGHT = 1.0
_C.TRAIN.LOSS_DETACH_MASK = True
_C.TRAIN.LOSS_MASK_THRESHOLD = 0.5
_C.TRAIN.LOSS_VGG_WEIGHT = 1.0

_C.MODEL = CN()
_C.MODEL.PRETRAINED_LORA_PATH = None
_C.MODEL.ATTENTIONS_2ND_LEARN_BIAS = True
_C.MODEL.FREEZE_SD = True
_C.MODEL.EMA_POWER = 3 / 4

_C.PREPROCESS = CN()
_C.PREPROCESS.BILATERAL_KERNEL_SIZE = 13
_C.PREPROCESS.BILATERAL_SIGMA_D = 3.0
_C.PREPROCESS.BILATERAL_SIGMA_R = 0.075
_C.PREPROCESS.BILATERAL_FILTER_ITERATIONS = 4


_C.EVAL = CN()
_C.EVAL.BATCH_SIZE = 8

_C.ENV = CN()
_C.ENV.MULTI_GPU_TIMEOUT_SEC = 1800


def update_config(cfg, filepath, logger=None):
    cfg.defrost()
    cfg.merge_from_file(filepath)
    if logger is not None:
        with open(filepath, 'r') as f:
            logger.info(f'Config:\n{f.read()}')

    cfg.freeze()


if __name__ == '__main__':
    import sys
    with open(sys.argv[1], 'w') as f:
        print(_C, file=f)
